### ISSUE TITLE
Create strings file

### ISSUE THREAD

**Issue by wissol** [wissol/sppy#12]
Create a string file containing all the strings that would be printed to the user, to allow for easier localization of the app

(e.g. 
* strings_es -> spanish prompts 
* strings_ru russian -> russian prompts
        ... )

**Comment by csoliss** [comment]
I was thinking about that, I think it's better to create a file named "language.py" and there put all labels of languages and "settings.py" create a variable to define the language that we use, what do you think?

**Comment by wissol** [comment]
Yes, that has been floating in my mind for some while. Let's open the issue.

2015-01-05 13:29 GMT+00:00 csoliss <notifications@github.com>:

**Comment by csoliss** [comment]
It's almost ready, I still need change the label from several items
